package com.cannontech.common.pao.service;

public enum PaoProviderTableEnum {
	YUKONPAOBJECT,
	DEVICE,
	DEVICECARRIERSETTINGS,
	DEVICESCANRATE,
	DEVICEWINDOW,
	DEVICEDIALUPSETTINGS,
	DEVICEDIRECTCOMMSETTINGS,
	DEVICECBC,
	DEVICEADDRESS,
	REGULATOR,
	CAPCONTROLAREA,
	CAPCONTROLSPECIALAREA,
	CAPCONTROLSUBSTATION,
	CAPCONTROLSUBSTATIONBUS,
	CAPCONTROLFEEDER,
	CAPBANK,
	CAPBANKADDITIONAL,
	DIGIGATEWAY,
	ZBGATEWAY,
	ZBENDPOINT,
	;
}
