package com.cannontech.roles;

/**
 * @author aaron
 */
public interface OperatorRoleDefs extends RoleDefs {
	public static final int ADMINISTRATOR_ROLEID = OPERATOR_ROLEID_BASE;
	public static final int CONSUMER_INFO_ROLEID = OPERATOR_ROLEID_BASE - 1;
	public static final int METERING_ROLEID = OPERATOR_ROLEID_BASE - 2;
	// removed direct loadcontrol roleid = -3
	public static final int DIRECT_CURTAILMENT_ROLEID = OPERATOR_ROLEID_BASE - 4;
	public static final int ENERGY_BUYBACK_ROLEID = OPERATOR_ROLEID_BASE - 5;
	public static final int ESUBSTATION_DRAWINGS_ROLEID = OPERATOR_ROLEID_BASE - 6;
	public static final int ODDS_FOR_CONTROL_ROLEID = OPERATOR_ROLEID_BASE - 7;
	public static final int INVENTORY_ROLEID = OPERATOR_ROLEID_BASE - 9;
	public static final int WORK_ORDER_ROLEID = OPERATOR_ROLEID_BASE - 10;
	public static final int CI_CURTAILMENT_ROLEID = OPERATOR_ROLEID_BASE - 11;
	public static final int SCHEDULER_ROLEID = OPERATOR_ROLEID_BASE - 12;
		
	static final int ADMINISTRATOR_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE;
	static final int CONSUMER_INFO_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 100;
	static final int METERING_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 200;
	// removed removed direct loadcontrol rolepropertyid = -300
	static final int DIRECT_CURTAILMENT_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 400;
	static final int ENERGY_BUYBACK_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 500;
	static final int ESUBSTATION_DRAWINGS_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 600;
	static final int ODDS_FOR_CONTROL_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 700;
	static final int CONSUMER_INFO_PROPERTYID_BASE2 = OPERATOR_PROPERTYID_BASE - 800;
	static final int INVENTORY_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 900;
	static final int WORK_ORDER_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 1000;
	static final int CI_CURTAILMENT_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 1100;
	static final int SCHEDULER_PROPERTYID_BASE = OPERATOR_PROPERTYID_BASE - 1200;

}
