/*
 *  These defines are for the DIALUPREPLY structure and define positions in the
 *  I/FResponse arrays.
 */

#ifndef _DUPREPLY_H_
#define _DUPREPLY_H_

#define DIAL_I_COMM_STATUS         0
#define DIAL_I_ACKNAK_STATUS       0
#define DIAL_I_METER_STATUS        1
#define DIAL_I_COMP_STATE          2
#define DIAL_I_CLASS_NUMBER        3

#define DIAL_I_CUMOUT              5
#define DIAL_I_CUMDR               6
#define DIAL_I_SEARAT              7
#define DIAL_I_SYSTAT              8
#define DIAL_I_DATE_YEAR           9
#define DIAL_I_DATE_MONTH          10
#define DIAL_I_DATE_DAY            11
#define DIAL_I_DATE_HOUR           12
#define DIAL_I_DATE_MINUTE         13
#define DIAL_I_DATE_SECOND         14

#define DIAL_I_BLK1_PKA_YEAR       19
#define DIAL_I_BLK1_PKA_MONTH      20
#define DIAL_I_BLK1_PKA_DAY        21
#define DIAL_I_BLK1_PKA_HR         22
#define DIAL_I_BLK1_PKA_MN         23
#define DIAL_I_BLK2_PKA_YEAR       24
#define DIAL_I_BLK2_PKA_MONTH      25
#define DIAL_I_BLK2_PKA_DAY        26
#define DIAL_I_BLK2_PKA_HR         27
#define DIAL_I_BLK2_PKA_MN         28
#define DIAL_I_BLK1_PKB_YEAR       29
#define DIAL_I_BLK1_PKB_MONTH      30
#define DIAL_I_BLK1_PKB_DAY        31
#define DIAL_I_BLK1_PKB_HR         32
#define DIAL_I_BLK1_PKB_MN         33
#define DIAL_I_BLK2_PKB_YEAR       34
#define DIAL_I_BLK2_PKB_MONTH      35
#define DIAL_I_BLK2_PKB_DAY        36
#define DIAL_I_BLK2_PKB_HR         37
#define DIAL_I_BLK2_PKB_MN         38
#define DIAL_I_BLK1_PKC_YEAR       39
#define DIAL_I_BLK1_PKC_MONTH      40
#define DIAL_I_BLK1_PKC_DAY        41
#define DIAL_I_BLK1_PKC_HR         42
#define DIAL_I_BLK1_PKC_MN         43
#define DIAL_I_BLK2_PKC_YEAR       44
#define DIAL_I_BLK2_PKC_MONTH      45
#define DIAL_I_BLK2_PKC_DAY        46
#define DIAL_I_BLK2_PKC_HR         47
#define DIAL_I_BLK2_PKC_MN         48
#define DIAL_I_BLK1_PKD_YEAR       49
#define DIAL_I_BLK1_PKD_MONTH      50
#define DIAL_I_BLK1_PKD_DAY        51
#define DIAL_I_BLK1_PKD_HR         52
#define DIAL_I_BLK1_PKD_MN         53
#define DIAL_I_BLK2_PKD_YEAR       54
#define DIAL_I_BLK2_PKD_MONTH      55
#define DIAL_I_BLK2_PKD_DAY        56
#define DIAL_I_BLK2_PKD_HR         57
#define DIAL_I_BLK2_PKD_MN         58

#define DIAL_F_AVGPF               8
#define DIAL_F_ETKWH1              9
#define DIAL_F_AKW1                10
#define DIAL_F_BKW1                11
#define DIAL_F_CKW1                12
#define DIAL_F_DKW1                13
#define DIAL_F_AKWH1               14
#define DIAL_F_BKWH1               15
#define DIAL_F_CKWH1               16
#define DIAL_F_DKWH1               17
#define DIAL_F_BLK1                18
#define DIAL_F_ETKWH2              19
#define DIAL_F_AKW2                20
#define DIAL_F_BKW2                21
#define DIAL_F_CKW2                22
#define DIAL_F_DKW2                23
#define DIAL_F_AKWH2               24
#define DIAL_F_BKWH2               25
#define DIAL_F_CKWH2               26
#define DIAL_F_DKWH2               27
#define DIAL_F_BLK2                28
#define DIAL_F_AKWCUM1             29
#define DIAL_F_BKWCUM1             30
#define DIAL_F_CKWCUM1             31
#define DIAL_F_DKWCUM1             32
#define DIAL_F_EKVARH1             33
#define DIAL_F_AKWC1               34
#define DIAL_F_BKWC1               35
#define DIAL_F_CKWC1               36
#define DIAL_F_DKWC1               37
#define DIAL_F_EKVARH2             38
#define DIAL_F_AKWCUM2             29
#define DIAL_F_BKWCUM2             40
#define DIAL_F_CKWCUM2             41
#define DIAL_F_DKWCUM2             42
#define DIAL_F_EKVARH3             43
#define DIAL_F_AKWC2               44
#define DIAL_F_BKWC2               45
#define DIAL_F_CKWC2               46
#define DIAL_F_DKWC2               47
#define DIAL_F_EKVARH4             48



#endif // _DUPREPLY_H_
