
#ifndef _TESTCMDPARSE_INPUT_
#define _TESTCMDPARSE_INPUT_

#include <string>

#define TEST_SIZE 96

std::string inputString[TEST_SIZE] = {
    "getvalue kwh",
      "control emetcon shed 1hr relay 1,2",
"control shed ?'NumMins'm",
"putconfig led yyy",
"putconfig service in",
"putconfig service out",
"control cycle terminate relay 3",
"control cycle terminate relay 2",
"control cycle terminate relay 1",
"control cycle 50 period 30 relay 1",
"control restore relay 3",
"control restore relay 2",
"control restore relay 1",
"control shed 5m relay 3",
"control shed 5m relay 2",
"control shed 5m relay 1",
"getvalue peak",
"putconfig emetcon timesync",
"getvalue voltage",
"getvalue demand",
"putconfig cold_load r1 10", 
"putconfig template '?LoadGroup'",
"putconfig cycle r1 50",
"putconfig xcom service in",
"putconfig xcom service out temp offhours 24",
"putconfig xcom main 0x01 0x80",
"putconfig xcom main 0x01 0x40",
"putconfig xcom raw 0x05 0x00",
"putstatus xcom prop inc",
"putconfig xcom raw 0x30 0x00 0x02 0x58",
"putconfig emetcon ied class 0 1",
"putconfig emetcon ied class 0 0",
"getvalue ied demand",
"putconfig emetcon ied class 72 2",
"putconfig emetcon ied class 72 1",
"getstatus eventlog",
"scan integrity",
"scan general",
"loop locate",
"putconfig emetcon install",
"getconfig role 1",
"putconfig led yyy",
"putstatus reset r1 r2 r3 cl",
"putconfig service in",
"putconfig service out",
"control cycle terminate",
"control cycle 50 period 30 count 4",
"control restore",
"control shed 60m",
"control shed 30m",
"control shed 15m",
"control shed 7.m",
"putstatus reset",
"loop 5",
"loop",
"ping",
"putstatus ovuv enable",
"putstatus ovuv disable",
"control close",
"control open",
"scan integrity",
"control restore",
"control shed 5m",
"putvalue ied reset",
"getconfig ied scan",
"getconfig ied time",
"getvalue ied kwh",
"getvalue ied demand",
"getconfig time sync",
"getconfig time",
"getstatus LP",
"getstatus external",
"control connect",
"control disconnect",
"getstatus disconnect",
"putconfig emetcon interval ?LP/LI",
"getconfig interval ?LP/LI",
"putconfig emetcon multiplier kyz1 ?Multiplier(x.xxx)",
"getconfig mult kyz 1",
"getstatus internal",
"getvalue powerfail",
"putvalue kyz 1 reset",
"getconfig model",
"getvalue demand",
"getvalue kWh",
"getconfig intervals lp",
"getconfig model",
"putvalue analog 1 3.14159",
"putvalue kyz 1 1.234",
"putstatus reset",
"putstatus powerfail reset",
"putvalue powerfail reset",
"getconfig raw start=0x93",
"getconfig function raw start=0x90832 2",
"putconfig emetcon raw start=0x9823 0x83 0x39 0x32",
"getvalue lp peak interval channel 2 12/31/2003 31"
      
    };


#endif
