package com.cannontech.web.updater.multispeak.deviceGroupSync;

public enum MultispeakDeviceGroupSyncUpdaterTypeEnum {

	METERS_PROCESSED_COUNT,
	SUBSTATION_CHANGE_COUNT,
	SUBSTATION_NO_CHANGE_COUNT,
	BILLING_CYCLE_CHANGE_COUNT,
	BILLING_CYCLE_NO_CHANGE_COUNT,
	IS_RUNNING,
	IS_NOT_RUNNING,
	IS_ABORTED,
	STATUS_TEXT,
	STATUS_TEXT_OR_LAST_SYNC_SUBSTATION,
	STATUS_TEXT_OR_LAST_SYNC_BILLING_CYCLE,
	STATUS_CLASS,
	HAS_LINKABLE_PROGRESS_SUBSTATION,
	NO_LINKABLE_PROGRESS_SUBSTATION,
	HAS_LINKABLE_PROGRESS_BILLING_CYCLE,
	NO_LINKABLE_PROGRESS_BILLING_CYCLE,
	LAST_COMPLETED_SYNC_SUBSTATION,
	LAST_COMPLETED_SYNC_BILLING_CYCLE,
	;
}
