/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CCItemCommand_TYPES_H
#define CCItemCommand_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "CCCommand_types.h"


namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class CCItemCommand;


class CCItemCommand : public virtual ::apache::thrift::TBase {
 public:

  CCItemCommand(const CCItemCommand&);
  CCItemCommand& operator=(const CCItemCommand&);
  CCItemCommand() : _itemId(0) {
  }

  virtual ~CCItemCommand() noexcept;
   ::Cti::Messaging::Serialization::Thrift::CCCommand _baseMessage;
  int32_t _itemId;

  void __set__baseMessage(const  ::Cti::Messaging::Serialization::Thrift::CCCommand& val);

  void __set__itemId(const int32_t val);

  bool operator == (const CCItemCommand & rhs) const
  {
    if (!(_baseMessage == rhs._baseMessage))
      return false;
    if (!(_itemId == rhs._itemId))
      return false;
    return true;
  }
  bool operator != (const CCItemCommand &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CCItemCommand & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(CCItemCommand &a, CCItemCommand &b);

std::ostream& operator<<(std::ostream& out, const CCItemCommand& obj);

}}}} // namespace

#endif
