/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CCShutdown_CONSTANTS_H
#define CCShutdown_CONSTANTS_H

#include "CCShutdown_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class CCShutdownConstants {
 public:
  CCShutdownConstants();

};

extern const CCShutdownConstants g_CCShutdown_constants;

}}}} // namespace

#endif
