/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CCSubstations_CONSTANTS_H
#define CCSubstations_CONSTANTS_H

#include "CCSubstations_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class CCSubstationsConstants {
 public:
  CCSubstationsConstants();

};

extern const CCSubstationsConstants g_CCSubstations_constants;

}}}} // namespace

#endif
