/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CCSystemStatus_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {


CCSystemStatus::~CCSystemStatus() noexcept {
}


void CCSystemStatus::__set__baseMessage(const  ::Cti::Messaging::Serialization::Thrift::CCMessage& val) {
  this->_baseMessage = val;
}

void CCSystemStatus::__set__systemState(const bool val) {
  this->_systemState = val;
}
std::ostream& operator<<(std::ostream& out, const CCSystemStatus& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t CCSystemStatus::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset__baseMessage = false;
  bool isset__systemState = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->_baseMessage.read(iprot);
          isset__baseMessage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->_systemState);
          isset__systemState = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset__baseMessage)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset__systemState)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t CCSystemStatus::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CCSystemStatus");

  xfer += oprot->writeFieldBegin("_baseMessage", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->_baseMessage.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("_systemState", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->_systemState);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CCSystemStatus &a, CCSystemStatus &b) {
  using ::std::swap;
  swap(a._baseMessage, b._baseMessage);
  swap(a._systemState, b._systemState);
}

CCSystemStatus::CCSystemStatus(const CCSystemStatus& other0) {
  _baseMessage = other0._baseMessage;
  _systemState = other0._systemState;
}
CCSystemStatus& CCSystemStatus::operator=(const CCSystemStatus& other1) {
  _baseMessage = other1._baseMessage;
  _systemState = other1._systemState;
  return *this;
}
void CCSystemStatus::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CCSystemStatus(";
  out << "_baseMessage=" << to_string(_baseMessage);
  out << ", " << "_systemState=" << to_string(_systemState);
  out << ")";
}

}}}} // namespace
