/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CCVerifyInactiveBanks_constants.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

const CCVerifyInactiveBanksConstants g_CCVerifyInactiveBanks_constants;

CCVerifyInactiveBanksConstants::CCVerifyInactiveBanksConstants() {
}

}}}} // namespace

