/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CCVerifyBanks_CONSTANTS_H
#define CCVerifyBanks_CONSTANTS_H

#include "CCVerifyBanks_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class CCVerifyBanksConstants {
 public:
  CCVerifyBanksConstants();

};

extern const CCVerifyBanksConstants g_CCVerifyBanks_constants;

}}}} // namespace

#endif
