/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CCVoltageRegulator_constants.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

const CCVoltageRegulatorConstants g_CCVoltageRegulator_constants;

CCVoltageRegulatorConstants::CCVoltageRegulatorConstants() {
}

}}}} // namespace

