/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CommErrorHistory_CONSTANTS_H
#define CommErrorHistory_CONSTANTS_H

#include "CommErrorHistory_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class CommErrorHistoryConstants {
 public:
  CommErrorHistoryConstants();

};

extern const CommErrorHistoryConstants g_CommErrorHistory_constants;

}}}} // namespace

#endif
