/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Command_CONSTANTS_H
#define Command_CONSTANTS_H

#include "Command_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class CommandConstants {
 public:
  CommandConstants();

};

extern const CommandConstants g_Command_constants;

}}}} // namespace

#endif
