/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EdgeDrBroadcastResponse_CONSTANTS_H
#define EdgeDrBroadcastResponse_CONSTANTS_H

#include "EdgeDrBroadcastResponse_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class EdgeDrBroadcastResponseConstants {
 public:
  EdgeDrBroadcastResponseConstants();

};

extern const EdgeDrBroadcastResponseConstants g_EdgeDrBroadcastResponse_constants;

}}}} // namespace

#endif
