/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EdgeDrError_TYPES_H
#define EdgeDrError_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

struct EdgeDrErrorType {
  enum type {
    TIMEOUT = 1
  };
};

extern const std::map<int, const char*> _EdgeDrErrorType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const EdgeDrErrorType::type& val);

std::string to_string(const EdgeDrErrorType::type& val);

class EdgeDrError;


class EdgeDrError : public virtual ::apache::thrift::TBase {
 public:

  EdgeDrError(const EdgeDrError&);
  EdgeDrError& operator=(const EdgeDrError&);
  EdgeDrError() : errorType((EdgeDrErrorType::type)0), errorMessage() {
  }

  virtual ~EdgeDrError() noexcept;
  EdgeDrErrorType::type errorType;
  std::string errorMessage;

  void __set_errorType(const EdgeDrErrorType::type val);

  void __set_errorMessage(const std::string& val);

  bool operator == (const EdgeDrError & rhs) const
  {
    if (!(errorType == rhs.errorType))
      return false;
    if (!(errorMessage == rhs.errorMessage))
      return false;
    return true;
  }
  bool operator != (const EdgeDrError &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EdgeDrError & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(EdgeDrError &a, EdgeDrError &b);

std::ostream& operator<<(std::ostream& out, const EdgeDrError& obj);

}}}} // namespace

#endif
