/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LMControlAreas_CONSTANTS_H
#define LMControlAreas_CONSTANTS_H

#include "LMControlAreas_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class LMControlAreasConstants {
 public:
  LMControlAreasConstants();

};

extern const LMControlAreasConstants g_LMControlAreas_constants;

}}}} // namespace

#endif
