/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LMEnergyExchangeControl_CONSTANTS_H
#define LMEnergyExchangeControl_CONSTANTS_H

#include "LMEnergyExchangeControl_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class LMEnergyExchangeControlConstants {
 public:
  LMEnergyExchangeControlConstants();

};

extern const LMEnergyExchangeControlConstants g_LMEnergyExchangeControl_constants;

}}}} // namespace

#endif
