/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Message_CONSTANTS_H
#define Message_CONSTANTS_H

#include "Message_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class MessageConstants {
 public:
  MessageConstants();

};

extern const MessageConstants g_Message_constants;

}}}} // namespace

#endif
