/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NotifEmail_TYPES_H
#define NotifEmail_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include "Message_types.h"


namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {


class NotifEmail {
 public:

  static const char* ascii_fingerprint; // = "16DE07F42813B37775F8BF399424BA2C";
  static const uint8_t binary_fingerprint[16]; // = {0x16,0xDE,0x07,0xF4,0x28,0x13,0xB3,0x77,0x75,0xF8,0xBF,0x39,0x94,0x24,0xBA,0x2C};

  NotifEmail() : _to(), _notifGroupId(0), _subject(), _body(), _toCc(), _toBcc() {
  }

  virtual ~NotifEmail() throw() {}

   ::Cti::Messaging::Serialization::Thrift::Message _baseMessage;
  std::string _to;
  int32_t _notifGroupId;
  std::string _subject;
  std::string _body;
  std::string _toCc;
  std::string _toBcc;

  void __set__baseMessage(const  ::Cti::Messaging::Serialization::Thrift::Message& val) {
    _baseMessage = val;
  }

  void __set__to(const std::string& val) {
    _to = val;
  }

  void __set__notifGroupId(const int32_t val) {
    _notifGroupId = val;
  }

  void __set__subject(const std::string& val) {
    _subject = val;
  }

  void __set__body(const std::string& val) {
    _body = val;
  }

  void __set__toCc(const std::string& val) {
    _toCc = val;
  }

  void __set__toBcc(const std::string& val) {
    _toBcc = val;
  }

  bool operator == (const NotifEmail & rhs) const
  {
    if (!(_baseMessage == rhs._baseMessage))
      return false;
    if (!(_to == rhs._to))
      return false;
    if (!(_notifGroupId == rhs._notifGroupId))
      return false;
    if (!(_subject == rhs._subject))
      return false;
    if (!(_body == rhs._body))
      return false;
    if (!(_toCc == rhs._toCc))
      return false;
    if (!(_toBcc == rhs._toBcc))
      return false;
    return true;
  }
  bool operator != (const NotifEmail &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NotifEmail & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(NotifEmail &a, NotifEmail &b);

}}}} // namespace

#endif
