/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NotifVoiceDataResponse_CONSTANTS_H
#define NotifVoiceDataResponse_CONSTANTS_H

#include "NotifVoiceDataResponse_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class NotifVoiceDataResponseConstants {
 public:
  NotifVoiceDataResponseConstants();

};

extern const NotifVoiceDataResponseConstants g_NotifVoiceDataResponse_constants;

}}}} // namespace

#endif
