/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NotifProgramAction_constants.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

const NotifProgramActionConstants g_NotifProgramAction_constants;

NotifProgramActionConstants::NotifProgramActionConstants() {
}

}}}} // namespace

