/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NotifResult_CONSTANTS_H
#define NotifResult_CONSTANTS_H

#include "NotifResult_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class NotifResultConstants {
 public:
  NotifResultConstants();

};

extern const NotifResultConstants g_NotifResult_constants;

}}}} // namespace

#endif
