/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NotifVoiceDataResponse_TYPES_H
#define NotifVoiceDataResponse_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include "Message_types.h"


namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {


class NotifVoiceDataResponse {
 public:

  static const char* ascii_fingerprint; // = "7559E3B3A20719652303821AF204C89B";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0x59,0xE3,0xB3,0xA2,0x07,0x19,0x65,0x23,0x03,0x82,0x1A,0xF2,0x04,0xC8,0x9B};

  NotifVoiceDataResponse() : _callToken(), _xmlData(), _contactId(0) {
  }

  virtual ~NotifVoiceDataResponse() throw() {}

   ::Cti::Messaging::Serialization::Thrift::Message _baseMessage;
  std::string _callToken;
  std::string _xmlData;
  int32_t _contactId;

  void __set__baseMessage(const  ::Cti::Messaging::Serialization::Thrift::Message& val) {
    _baseMessage = val;
  }

  void __set__callToken(const std::string& val) {
    _callToken = val;
  }

  void __set__xmlData(const std::string& val) {
    _xmlData = val;
  }

  void __set__contactId(const int32_t val) {
    _contactId = val;
  }

  bool operator == (const NotifVoiceDataResponse & rhs) const
  {
    if (!(_baseMessage == rhs._baseMessage))
      return false;
    if (!(_callToken == rhs._callToken))
      return false;
    if (!(_xmlData == rhs._xmlData))
      return false;
    if (!(_contactId == rhs._contactId))
      return false;
    return true;
  }
  bool operator != (const NotifVoiceDataResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NotifVoiceDataResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(NotifVoiceDataResponse &a, NotifVoiceDataResponse &b);

}}}} // namespace

#endif
