/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NotifProgramAction_CONSTANTS_H
#define NotifProgramAction_CONSTANTS_H

#include "NotifProgramAction_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class NotifProgramActionConstants {
 public:
  NotifProgramActionConstants();

};

extern const NotifProgramActionConstants g_NotifProgramAction_constants;

}}}} // namespace

#endif
