/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Registration_TYPES_H
#define Registration_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include "Message_types.h"


namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {


class Registration {
 public:

  static const char* ascii_fingerprint; // = "C2204ADD0A0730ECBED9A40D93FF4569";
  static const uint8_t binary_fingerprint[16]; // = {0xC2,0x20,0x4A,0xDD,0x0A,0x07,0x30,0xEC,0xBE,0xD9,0xA4,0x0D,0x93,0xFF,0x45,0x69};

  Registration() : _appName(), _appId(0), _appIsUnique(0), _appKnownPort(0), _appExpirationDelay(0) {
  }

  virtual ~Registration() throw() {}

   ::Cti::Messaging::Serialization::Thrift::Message _baseMessage;
  std::string _appName;
  int32_t _appId;
  int32_t _appIsUnique;
  int32_t _appKnownPort;
  int32_t _appExpirationDelay;

  void __set__baseMessage(const  ::Cti::Messaging::Serialization::Thrift::Message& val) {
    _baseMessage = val;
  }

  void __set__appName(const std::string& val) {
    _appName = val;
  }

  void __set__appId(const int32_t val) {
    _appId = val;
  }

  void __set__appIsUnique(const int32_t val) {
    _appIsUnique = val;
  }

  void __set__appKnownPort(const int32_t val) {
    _appKnownPort = val;
  }

  void __set__appExpirationDelay(const int32_t val) {
    _appExpirationDelay = val;
  }

  bool operator == (const Registration & rhs) const
  {
    if (!(_baseMessage == rhs._baseMessage))
      return false;
    if (!(_appName == rhs._appName))
      return false;
    if (!(_appId == rhs._appId))
      return false;
    if (!(_appIsUnique == rhs._appIsUnique))
      return false;
    if (!(_appKnownPort == rhs._appKnownPort))
      return false;
    if (!(_appExpirationDelay == rhs._appExpirationDelay))
      return false;
    return true;
  }
  bool operator != (const Registration &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Registration & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Registration &a, Registration &b);

}}}} // namespace

#endif
