/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Registration_constants.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

const RegistrationConstants g_Registration_constants;

RegistrationConstants::RegistrationConstants() {
}

}}}} // namespace

