/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RfnAddressing_constants.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift { namespace Rfn {

const RfnAddressingConstants g_RfnAddressing_constants;

RfnAddressingConstants::RfnAddressingConstants() {
}

}}}}} // namespace

