/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RfnMeterReadRequest_constants.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

const RfnMeterReadRequestConstants g_RfnMeterReadRequest_constants;

RfnMeterReadRequestConstants::RfnMeterReadRequestConstants() {
}

}}}} // namespace

