/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RfnWaterNodeConfigMessages_constants.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

const RfnWaterNodeConfigMessagesConstants g_RfnWaterNodeConfigMessages_constants;

RfnWaterNodeConfigMessagesConstants::RfnWaterNodeConfigMessagesConstants() {
}

}}}} // namespace

