/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ServerRequest_CONSTANTS_H
#define ServerRequest_CONSTANTS_H

#include "ServerRequest_types.h"

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

class ServerRequestConstants {
 public:
  ServerRequestConstants();

};

extern const ServerRequestConstants g_ServerRequest_constants;

}}}} // namespace

#endif
