/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Trace_TYPES_H
#define Trace_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include "Message_types.h"


namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {


class Trace {
 public:

  static const char* ascii_fingerprint; // = "CE734438801AE7158180E811AD3838C7";
  static const uint8_t binary_fingerprint[16]; // = {0xCE,0x73,0x44,0x38,0x80,0x1A,0xE7,0x15,0x81,0x80,0xE8,0x11,0xAD,0x38,0x38,0xC7};

  Trace() : _end(0), _attributes(0), _trace() {
  }

  virtual ~Trace() throw() {}

   ::Cti::Messaging::Serialization::Thrift::Message _baseMessage;
  bool _end;
  int32_t _attributes;
  std::string _trace;

  void __set__baseMessage(const  ::Cti::Messaging::Serialization::Thrift::Message& val) {
    _baseMessage = val;
  }

  void __set__end(const bool val) {
    _end = val;
  }

  void __set__attributes(const int32_t val) {
    _attributes = val;
  }

  void __set__trace(const std::string& val) {
    _trace = val;
  }

  bool operator == (const Trace & rhs) const
  {
    if (!(_baseMessage == rhs._baseMessage))
      return false;
    if (!(_end == rhs._end))
      return false;
    if (!(_attributes == rhs._attributes))
      return false;
    if (!(_trace == rhs._trace))
      return false;
    return true;
  }
  bool operator != (const Trace &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Trace & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Trace &a, Trace &b);

}}}} // namespace

#endif
