/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Trace_types.h"

#include <algorithm>

namespace Cti { namespace Messaging { namespace Serialization { namespace Thrift {

const char* Trace::ascii_fingerprint = "CE734438801AE7158180E811AD3838C7";
const uint8_t Trace::binary_fingerprint[16] = {0xCE,0x73,0x44,0x38,0x80,0x1A,0xE7,0x15,0x81,0x80,0xE8,0x11,0xAD,0x38,0x38,0xC7};

uint32_t Trace::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset__baseMessage = false;
  bool isset__end = false;
  bool isset__attributes = false;
  bool isset__trace = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->_baseMessage.read(iprot);
          isset__baseMessage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->_end);
          isset__end = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->_attributes);
          isset__attributes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->_trace);
          isset__trace = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset__baseMessage)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset__end)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset__attributes)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset__trace)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t Trace::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("Trace");

  xfer += oprot->writeFieldBegin("_baseMessage", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->_baseMessage.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("_end", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->_end);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("_attributes", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->_attributes);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("_trace", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->_trace);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Trace &a, Trace &b) {
  using ::std::swap;
  swap(a._baseMessage, b._baseMessage);
  swap(a._end, b._end);
  swap(a._attributes, b._attributes);
  swap(a._trace, b._trace);
}

}}}} // namespace
