package com.cannontech.common.device.groups.dao;

public enum DeviceGroupType {
    STATIC,
    ROLODEX,
    ROUTE,
    SUBSTATION_TO_ROUTE,
    DEVICETYPE,
    DEVICETAG,
    DEVICECONFIG,
    METERS_SCANNING_LOAD_PROFILE,
    METERS_SCANNING_VOLTAGE_PROFILE,
    METERS_SCANNING_INTEGRITY,
    METERS_SCANNING_ACCUMULATOR,
    METERS_DISABLED,
    COMPOSED,
    METERS_DISCONNECT_COLLAR,
    ATTRIBUTE_DEFINED,
    ATTRIBUTE_EXISTS,
    METERS_METER_PROGRAMMING,
    METERS_ALL_PLC_METERS,
    METERS_ALL_RF_ELECTRIC_METERS,
    METERS_ALL_RFW_METERS,
    METERS_ALL_RFG_METERS,
    LOAD_GROUPS,
    LOAD_PROGRAMS,
    ;
}
