package com.cannontech.common.events.loggers;

public enum ArgEnum {
    accountNumber, 
    applianceType, 
    commandRequestExecutionContextId, 
    commandRequestExecutionId, 
    commandRequestExecutionType, 
    commandScheduleId,
    contactName, 
    controlAreaName, 
    deviceLabel, 
    deviceName, 
    fileName, 
    gearName, 
    loadGroupName,
    meterName,
    paoId, 
    paoName, 
    paoType, 
    pointDate, 
    pointId, 
    pointOffset, 
    pointType, 
    pointValue, 
    programName, 
    remoteAddress, 
    scenarioName, 
    scheduleName, 
    serialNumber, 
    shedDuration, 
    tagSet, 
    taskName,
    thermostatLabel,
    username, 
    workOrderNumber,
    inventoryId,
    errorDescription,
    porter,
    errorCode,
    category
    ;

}
