package com.cannontech.dbeditor.editor.point;

/**
 * This class was generated by a SmartGuide.
 * 
 */

import java.util.Vector;
import javax.swing.table.AbstractTableModel;
import javax.swing.event.TableModelEvent;

public class FDRTranslationTableModel extends AbstractTableModel 
{
	private Vector columnNames = new Vector();

	//each row here is just a Vector of Strings
	private Vector rows = new Vector();
/**
 * This method was created in VisualAge.
 */
public FDRTranslationTableModel() {
	super();
}
/**
 * Insert the method's description here.
 * Creation date: (6/15/00 2:54:45 PM)
 * @param newRow java.util.Vector
 */
public void addRow(Vector newRow) 
{
	rows.addElement(newRow);
	fireTableRowsInserted(rows.size()-1,rows.size()-1);
}
/**
 * Insert the method's description here.
 * Creation date: (6/15/00 2:54:45 PM)
 * @param newRow java.util.Vector
 */
public void editRow(int position, Vector newRow) {
	rows.remove(position);
	rows.add(position, newRow);
	fireTableRowsUpdated(position, position);
}
public int getColumnCount() {
	return columnNames.size();
}
/* Created
*/
public String getColumnName(int column) {
	return columnNames.elementAt(column).toString();
}
/**
 * Insert the method's description here.
 * Creation date: (5/30/2001 4:35:11 PM)
 * @param row int
 */
public Vector getRowAt(int row) 
{
	if( row < 0 || row >= getRowCount() || !(rows.get(row) instanceof Vector) )
		return null;
	else
		return (Vector)rows.get(row);
}
// Data methods

public int getRowCount() {
	return rows.size();
}
public Object getValueAt(int aRow, int aColumn)
{
	Vector row = (Vector) rows.elementAt(aRow);
	return row.elementAt(aColumn);
}
/**
 * This method was created in VisualAge.
 */
private void initColumns() 
{	
	rows.removeAllElements();
	columnNames.removeAllElements();

	columnNames = new Vector( 3 );
	columnNames.addElement("Direction");
	columnNames.addElement("Interface");
	columnNames.addElement("Translation");

	fireTableStructureChanged(); // Tell the listeners a new table has arrived.
}
public boolean isCellEditable(int row, int column) {

	// make every cell non-editable
	return false;

}
/**
 * This method creates the table
 */
 
public void makeTable ( )
{
	initColumns();
}
/**
 * Insert the method's description here.
 * Creation date: (6/15/00 2:54:45 PM)
 * @param newRow java.util.Vector
 */
public void removeRow(int position) {
	rows.remove(position);
	fireTableRowsDeleted(position, position);
}
/**
 * This method was created in VisualAge.
 */
public void reset() 
{
	if ( columnNames != null )
		columnNames.removeAllElements();

	if ( rows != null )
		rows.removeAllElements();

	fireTableChanged(null);
}
}
