package com.cannontech.common.config;

public enum MasterConfigBooleanKeysEnum {

    BULK_IMPORTER_SINGLE_GROUP,	//option to limit membership to only 1 child group per parent group.
    CYME_ENABLED,
    DEFAULT_ENERGY_COMPANY_EDIT,
    DEVELOPMENT_MODE,
    DIGI_ENABLED,
    DIGI_SMARTPOLL_ENABLED,
    DISABLE_ANALYTICS,
    ENABLE_INVENTORY_SAVE_TO_FILE,
    ENABLE_SETTLEMENTS,
	ENABLE_WEB_DEBUG_PAGES,
	I18N_DESIGN_MODE,
    MSP_ENABLE_ALTGROUP_EXTENSION,          //YUK-10787
    MSP_ENABLE_SUBSTATIONNAME_EXTENSION,    //YUK-10787
    RFN_METER_DISCONNECT_ARMING,
	SHOW_ONE_WAY_ENCRYPT,
	USE_OLD_FORGOTTEN_PASSWORD_PAGE,
	VIRTUAL_PROGRAMS,
	;
}