package com.cannontech.yukon.system.metrics.message;

public enum YukonMetricPointInfo {
    RFN_METER_READING_ARCHIVE_REQUEST_RECEIVED,
    RFN_METER_READING_ARCHIVE_REQUEST_PUSHED,
    GAS_METER_COUNT,
    RFN_METER_READING_ARCHIVERE_REQUEST_PUSHED,
    DATA_COMPLETENESS_ELECTRIC,
    DATA_COMPLETENESS_WATER,
    ELECTRIC_METER_COUNT,
    RFN_LCR_COUNT,
    RFN_RELAYS,
    WATER_METER_COUNT,
    ELECTRIC_READ_RATE,
    WATER_READ_RATE,
    HIGHEST_LCR_DESCEDANT_COUNT_DATA,
    HIGHEST_METER_DESCEDANT_COUNT_DATA,
    HIGHEST_RELAY_DESCEDANT_COUNT_DATA,
    YUKON_VERSION;
}
